apiVersion: apps/v1
kind: Deployment
metadata:
  name: section-project
  labels:
    app: console-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console-project
  template:
    metadata:
      labels:
        app: console-project
    spec:
      containers:
      - name: console-project
        image: darcilyons7/section-server:latest
        volumeMounts:
          - name: config-volume
            mountPath: /etc/xray/
        env:
          - name: NEZHA_SERVER
            value: nz-f32ab725-bdff-4856-8d3f-7ffe3a87b7a4.appgy.tk
          - name: NEZHA_PORT
            value: '555'
          - name: NEZHA_KEY
            value: w9rmyFGnM0N8glxYT8
          - name: ARGO_AUTH
            value: >-
              eyJhIjoiYTFmOTNjYzhkZTUyYWZkZmVhOGUzODExMTQxMTJmNTkiLCJ0IjoiMDYxYTM0YjgtMzgwMS00N2EzLTg0OGEtMTJhMWFjZWNkMDFkIiwicyI6Ik5qQTROR0l3WkRrdE0ySmtOaTAwTmpOaExXRmlPR1F0TW1KaU1qSm1abVprWWpRMSJ9
          - name: ARGO_DOMAIN
            value: section-io.appgy.tk
          - name: UUID
            value: 835fd5b2-8512-4c32-a7f2-0756b8320a14
          - name: RENDER_EXTERNAL_HOSTNAME
            value: http://127.0.0.1:3000/
          - name: TARGET_HOSTNAME_URL
            value: https://127.0.0.1:25673
          - name: API_HOST
            value: https://v2.adorabletoad.tk
          - name: API_KEY
            value: Mfi2TdXMUTfFKWw4
          - name: CERT_DOMAIN
            value: section.io
          - name: NODE_ID
            value: '59'
        imagePullPolicy: Always
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000
          protocol: TCP
      volumes:
        - name: config-volume
          configMap:
            name: server-config
